// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// process_patient
List process_patient(int i, NumericVector time, NumericVector hazard12, NumericVector hazard13, NumericVector h12, NumericVector lp12, NumericVector lp13, NumericMatrix c1, NumericMatrix c2, DataFrame patient_data, int m, double onset_rate);
RcppExport SEXP _MIPD_process_patient(SEXP iSEXP, SEXP timeSEXP, SEXP hazard12SEXP, SEXP hazard13SEXP, SEXP h12SEXP, SEXP lp12SEXP, SEXP lp13SEXP, SEXP c1SEXP, SEXP c2SEXP, SEXP patient_dataSEXP, SEXP mSEXP, SEXP onset_rateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type time(timeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type hazard12(hazard12SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type hazard13(hazard13SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type h12(h12SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lp12(lp12SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lp13(lp13SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type c1(c1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type c2(c2SEXP);
    Rcpp::traits::input_parameter< DataFrame >::type patient_data(patient_dataSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type onset_rate(onset_rateSEXP);
    rcpp_result_gen = Rcpp::wrap(process_patient(i, time, hazard12, hazard13, h12, lp12, lp13, c1, c2, patient_data, m, onset_rate));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MIPD_process_patient", (DL_FUNC) &_MIPD_process_patient, 12},
    {NULL, NULL, 0}
};

RcppExport void R_init_MIPD(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
