#' A list of fitted models under Markov assumption

#' @format
#' A `list` of 10 elements, where each element is a `list` of 3 elements. Each sublist contains
#' the parameter estimates (estimands) for a specific transition, obtained from the respective fitted model.
#'
#' @source
#' Estimands generated by fitting parametric models over datasets that were generated using multiple imputation.
"all_fits_MM"
