# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

process_patient <- function(i, time, hazard12, hazard13, h12, lp12, lp13, c1, c2, patient_data, m, onset_rate) {
    .Call(`_MIPD_process_patient`, i, time, hazard12, hazard13, h12, lp12, lp13, c1, c2, patient_data, m, onset_rate)
}

